import type { Feedback } from '@/types'

// Feedback library for the Capstone Simulator (analyzes the integrated design, not
// the learner — FB-002). Each entry ties one system layer back to its arc; the
// capstone fails if it ignores observability/maintainability/security (PH-903).
export const capFeedback = {
  contextMismatch: {
    id: 'FB-CAP-CONTEXT',
    severity: 'risk',
    decision: 'Die Context-Strategie trägt das System über Monate nicht.',
    consequence: 'Ohne Control Plane verliert das Projekt Constraints; der Hot-Context wird zu Noise.',
    realWorldContext: 'Multi-Session-Agentenarbeit braucht durable State + bounded Context + Isolation (ARC-02/06).',
    failureMode: 'Verlorene Entscheidungen und Context-Noise über die Zeit.',
    architectureRule: 'Stabile Regeln + durable Progress-Memory + isolierte Subagent-Contexts statt „alles laden“.',
    improvedSolution: 'Control Plane aus Control-Docs + Progress-Memory; Worker liefern Summaries.',
    reviewHook: 'capstone_transfer',
  },
  toolsMismatch: {
    id: 'FB-CAP-TOOLS',
    severity: 'risk',
    decision: 'Die Tool-Grenzen für die Agents sind zu weit.',
    consequence: 'Ein mehrdeutiger Task kann irreversible oder teure Aktionen auslösen.',
    realWorldContext: 'Agents brauchen typed Tool-Contracts + Least Privilege + Approval bei high-impact (ARC-03/08).',
    failureMode: 'Unkontrollierte Tool-Wirkung und unklare Ownership.',
    architectureRule: 'Minimale, typisierte Tool-Contracts; Approval-Gate für riskante Aktionen.',
    improvedSolution: 'Scope einschränken, Output-Contract definieren, high-impact hinter Approval legen.',
    reviewHook: 'capstone_transfer',
  },
  retrievalMismatch: {
    id: 'FB-CAP-RETRIEVAL',
    severity: 'risk',
    decision: 'Die Retrieval-Entscheidung passt nicht zum Korpus.',
    consequence: 'Entweder fehlt Evidenz über Code/Docs, oder du baust Retrieval, wo es (noch) keinen Korpus gibt.',
    realWorldContext: 'Hybrid + Reranking lohnt bei großem Code/Docs-Korpus; ohne Korpus ist Retrieval verfrüht (ARC-05).',
    failureMode: 'Ungegroundete Antworten — oder unnötige Pipeline-Komplexität.',
    architectureRule: 'Retrieval an den tatsächlichen Korpus koppeln; Methode nach Query/Dokument wählen.',
    improvedSolution: 'Großer Code/Docs-Korpus → Hybrid + Reranking; früher Prototyp ohne Korpus → noch kein Retrieval.',
    reviewHook: 'retrieval_method_transfer',
  },
  evalMismatch: {
    id: 'FB-CAP-EVAL',
    severity: 'critical',
    decision: 'Das System hat keine belastbare Verlässlichkeits-Messung.',
    consequence: 'Du erkennst Regressionen und falsche Antworten erst beim Nutzer — das System ist nicht kontrollierbar.',
    realWorldContext: 'Ein Capstone ohne Eval/Observability ist nicht zulässig (PH-903); Task-Erfolg + Regression sind Pflicht (ARC-07).',
    failureMode: 'Perfekt klingendes, untestbares Design.',
    architectureRule: 'Miss echten Task-Erfolg + Regression-Set immer; Grounding wo Quellen im Spiel sind.',
    improvedSolution: 'Eval-Harness mit Erfolgsfällen, Regression-Set und Grounding-Checks ergänzen.',
    reviewHook: 'eval_transfer',
  },
  securityMismatch: {
    id: 'FB-CAP-SECURITY',
    severity: 'critical',
    decision: 'Die Sicherheits-/Governance-Grenzen fehlen oder sind zu schwach.',
    consequence: 'Agents können destruktive Aktionen ausführen oder durch untrusted Input manipuliert werden.',
    realWorldContext: 'Least Privilege + Approval-Gates + Input-Isolation + Sandbox sind Capstone-Pflicht (ARC-08, PH-903).',
    failureMode: 'Kein Approval-Gate, keine Sandbox, kein Schutz gegen Injection.',
    architectureRule: 'Least Privilege, Approval für high-impact, untrusted Input als Daten, Sandbox für Risiko.',
    improvedSolution: 'Governance-Layer ergänzen: Permissions minimieren, Approval-Gates, Input isolieren, sandboxen.',
    reviewHook: 'security_incident_transfer',
  },
  repoMismatch: {
    id: 'FB-CAP-REPO',
    severity: 'risk',
    decision: 'Das System bleibt für Menschen und Agents nicht wartbar.',
    consequence: 'Über Monate und mehrere Beteiligte wird Wissen zum Bottleneck; Änderungen werden riskant.',
    realWorldContext: 'Lesbare Struktur + kleine Units + Source-Material control plane halten es wartbar (ARC-09).',
    failureMode: 'Tribal Knowledge, Monster-Files, verlorene Entscheidungen.',
    architectureRule: 'Lesbares Repo, kleine Units, durable Docs als Control Plane — Wissen in Artefakte, nicht Köpfe.',
    improvedSolution: 'Feature-Folder + Konventionen + Decision-Log/Ledger als geteilte Control Plane.',
    reviewHook: 'team_scale_transfer',
  },
  clean: {
    id: 'FB-CAP-CLEAN',
    severity: 'strong',
    decision: 'Eine integrierte Architektur: Context, Tools, Retrieval, Eval, Security und Repo greifen zusammen.',
    consequence: 'Das System bleibt verständlich, testbar, kontrollierbar und wartbar — auch über Monate und im Team.',
    realWorldContext: 'Genau das ist die Capstone-Frage: ein AI-gestütztes Dev-System, das über Zeit beherrschbar bleibt.',
    failureMode: 'Vermieden: glänzendes, aber untestbares/unkontrollierbares Design.',
    architectureRule: 'So komplex wie nötig, so einfach wie möglich — jede Ebene mit klarer Begründung und Grenze.',
    improvedSolution: 'Nächste Stufen: Failure Injection überstehen (10-03), Eval/Governance schärfen (10-04), verteidigen (10-05).',
    reviewHook: 'capstone_transfer',
  },
} satisfies Record<string, Feedback>
