import type { RoadmapNode } from '@/types'
import { LAB } from '@/content/labs/labs'

// Roadmap nodes transcribed from domain/11_curriculum_graph.md NODE_REGISTRY.
// Structure + prerequisites are the durable graph; `purpose` is a short German
// preview line (RD-201). No lesson *bodies* here — those arrive in PHASE_3.
export const nodes: RoadmapNode[] = [
  {
    id: 'NODE-00-01', arcId: 'ARC-00', order: 1,
    title: 'What AI Engineering Actually Builds',
    purpose: 'Feature-Demo von verlässlichem AI-System unterscheiden.',
    outcome: 'distinguish feature demo from reliable AI-native system.',
    conceptIds: ['CONCEPT-AIE-001'], prerequisites: [], unlocks: ['NODE-00-02'],
    labIds: [LAB.failureModeTree], lessonModes: ['task-first', 'multiple-viewpoints'],
  },
  {
    id: 'NODE-00-02', arcId: 'ARC-00', order: 2,
    title: 'The Iceberg Model',
    purpose: 'Versteckte Layers unter einem AI-Feature sehen.',
    outcome: 'see hidden layers beneath visible AI feature.',
    conceptIds: ['CONCEPT-AIE-003'], prerequisites: ['NODE-00-01'], unlocks: ['NODE-01-01'],
    labIds: [LAB.layerStackBuilder], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-01-01', arcId: 'ARC-01', order: 3,
    title: 'Augmented LLM',
    purpose: 'Model + Tools + Retrieval + Memory als Basiseinheit.',
    outcome: 'model + tools + retrieval + memory as base unit.',
    conceptIds: ['CONCEPT-AIE-002'], prerequisites: ['NODE-00-02'], unlocks: ['NODE-01-02'],
    labIds: [LAB.architectureBuilder], lessonModes: ['term-first', 'architecture-builder'],
  },
  {
    id: 'NODE-01-02', arcId: 'ARC-01', order: 4,
    title: 'Simplicity Before Agency',
    purpose: 'Einfachste messbare Architektur wählen.',
    outcome: 'choose simplest measurable architecture.',
    conceptIds: ['CONCEPT-AIE-004', 'CONCEPT-PROD-001'], prerequisites: ['NODE-01-01'], unlocks: ['NODE-01-03'],
    labIds: [LAB.tradeOffDuel], lessonModes: ['trade-off-first'],
  },
  {
    id: 'NODE-01-03', arcId: 'ARC-01', order: 5,
    title: 'System Layers Map',
    purpose: 'Fehler nach System-Layer klassifizieren.',
    outcome: 'classify failures by system layer.',
    conceptIds: ['LAYER-01', 'LAYER-02', 'LAYER-03', 'LAYER-04', 'LAYER-05', 'LAYER-06', 'LAYER-07', 'LAYER-08', 'LAYER-09'],
    prerequisites: ['NODE-01-02'], unlocks: ['NODE-02-01'],
    labIds: [LAB.layerStackBuilder], lessonModes: ['multiple-viewpoints'],
  },
  {
    id: 'NODE-02-01', arcId: 'ARC-02', order: 6,
    title: 'Context Window and Token Budget',
    purpose: 'Endlichen Context bewusst zuteilen.',
    outcome: 'allocate finite context intentionally.',
    conceptIds: ['CONCEPT-CTX-001', 'CONCEPT-CTX-002'], prerequisites: ['NODE-01-03'], unlocks: ['NODE-02-02'],
    labIds: [LAB.contextAllocator, LAB.contextBudgetBoard], lessonModes: ['term-first'],
  },
  {
    id: 'NODE-02-02', arcId: 'ARC-02', order: 7,
    title: 'Context Noise',
    purpose: 'Schädlichen irrelevanten/veralteten Context erkennen.',
    outcome: 'identify harmful irrelevant/stale context.',
    conceptIds: ['CONCEPT-CTX-003'], prerequisites: ['NODE-02-01'], unlocks: ['NODE-02-03'],
    labIds: [LAB.contextBudgetBoard, LAB.failureModeTree], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-02-03', arcId: 'ARC-02', order: 8,
    title: 'Context Compression',
    purpose: 'Durable State ohne Verlust von Constraints zusammenfassen.',
    outcome: 'summarize durable state without losing constraints.',
    conceptIds: ['CONCEPT-CTX-004'], prerequisites: ['NODE-02-02'], unlocks: ['NODE-02-04'],
    labIds: [LAB.contextBudgetBoard], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-02-04', arcId: 'ARC-02', order: 9,
    title: 'Context Isolation and Subagents',
    purpose: 'Noisy Exploration in separaten Context auslagern.',
    outcome: 'move noisy exploration into separate context.',
    conceptIds: ['CONCEPT-CTX-005'], prerequisites: ['NODE-02-03'], unlocks: ['NODE-03-01'],
    labIds: [LAB.agentTraceDebugger], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-03-01', arcId: 'ARC-03', order: 10,
    title: 'Tools Are Interfaces',
    purpose: 'Tools als Agent-Computer-Interfaces gestalten.',
    outcome: 'design tools as agent-computer interfaces.',
    conceptIds: ['CONCEPT-TOOL-001', 'CONCEPT-TOOL-002'], prerequisites: ['NODE-02-04'], unlocks: ['NODE-03-02'],
    labIds: [LAB.toolContractForge], lessonModes: ['term-first', 'task-first'],
  },
  {
    id: 'NODE-03-02', arcId: 'ARC-03', order: 11,
    title: 'Structured Outputs',
    purpose: 'Downstream-Parsing- und Format-Drift verhindern.',
    outcome: 'prevent downstream parsing/format drift.',
    conceptIds: ['CONCEPT-TOOL-003'], prerequisites: ['NODE-03-01'], unlocks: ['NODE-03-03'],
    labIds: [LAB.constraintPuzzle, LAB.toolContractForge], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-03-03', arcId: 'ARC-03', order: 12,
    title: 'Constrained Decoding',
    purpose: 'Schema-Grenzen der Generierung verstehen.',
    outcome: 'understand schema-level generation constraints and limits.',
    conceptIds: ['CONCEPT-TOOL-004'], prerequisites: ['NODE-03-02'], unlocks: ['NODE-03-04'],
    labIds: [LAB.constraintPuzzle], lessonModes: ['term-first', 'constraint-puzzle'],
  },
  {
    id: 'NODE-03-04', arcId: 'ARC-03', order: 13,
    title: 'MCP and Tool Ecosystems',
    purpose: 'Standardisierte externe Tool-/Daten-Integration modellieren.',
    outcome: 'model standardized external tool/data integration.',
    conceptIds: ['CONCEPT-TOOL-005'], prerequisites: ['NODE-03-03'], unlocks: ['NODE-04-01'],
    labIds: [LAB.toolContractForge, LAB.architectureBuilder], lessonModes: ['architecture-builder'],
  },
  {
    id: 'NODE-04-01', arcId: 'ARC-04', order: 14,
    title: 'Workflow vs Agent',
    purpose: 'Vorhersehbaren Workflow vs autonomen Agent wählen.',
    outcome: 'choose predictable workflow vs autonomous agent.',
    conceptIds: ['CONCEPT-CF-001'], prerequisites: ['NODE-03-04'], unlocks: ['NODE-04-02'],
    labIds: [LAB.tradeOffDuel, LAB.agentTraceDebugger], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-04-02', arcId: 'ARC-04', order: 15,
    title: 'Workflow Patterns',
    purpose: 'Prompt Chaining, Routing und Parallelisierung komponieren.',
    outcome: 'compose prompt chaining, routing, and parallelization.',
    conceptIds: ['CONCEPT-CF-002', 'CONCEPT-CF-003', 'CONCEPT-CF-004'], prerequisites: ['NODE-04-01'], unlocks: ['NODE-04-03'],
    labIds: [LAB.architectureBuilder], lessonModes: ['architecture-builder'],
  },
  {
    id: 'NODE-04-03', arcId: 'ARC-04', order: 16,
    title: 'Orchestrator-Worker',
    purpose: 'Subtasks delegieren ohne Main-Context zu fluten.',
    outcome: 'delegate dynamic subtasks without flooding main context.',
    conceptIds: ['CONCEPT-CF-005'], prerequisites: ['NODE-04-02'], unlocks: ['NODE-04-04'],
    labIds: [LAB.agentTraceDebugger, LAB.architectureBuilder], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-04-04', arcId: 'ARC-04', order: 17,
    title: 'Evaluator-Optimizer',
    purpose: 'Verbesserungs-Loops mit Kriterien bauen.',
    outcome: 'build improvement loops with criteria.',
    conceptIds: ['CONCEPT-CF-006'], prerequisites: ['NODE-04-03'], unlocks: ['NODE-04-05'],
    labIds: [LAB.evalDesigner, LAB.agentTraceDebugger], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-04-05', arcId: 'ARC-04', order: 18,
    title: 'Autonomous Agent Loop',
    purpose: 'Plan-Act-Observe, Stop-Conditions, Fehler-Aufschaukeln.',
    outcome: 'reason about plan-act-observe loops, stop conditions, and compounding error.',
    conceptIds: ['CONCEPT-CF-007'], prerequisites: ['NODE-04-04'], unlocks: ['NODE-05-01'],
    labIds: [LAB.agentTraceDebugger], lessonModes: ['trace-first'],
  },
  {
    id: 'NODE-05-01', arcId: 'ARC-05', order: 19,
    title: 'RAG Basics',
    purpose: 'Basis-Retrieval-Pipeline bauen.',
    outcome: 'build basic retrieval pipeline.',
    conceptIds: ['CONCEPT-RET-001', 'CONCEPT-RET-002', 'CONCEPT-RET-003'], prerequisites: ['NODE-04-05'], unlocks: ['NODE-05-02'],
    labIds: [LAB.pipelineBuilder, LAB.retrievalFactory], lessonModes: ['architecture-builder'],
  },
  {
    id: 'NODE-05-02', arcId: 'ARC-05', order: 20,
    title: 'Lexical vs Semantic Retrieval',
    purpose: 'Retrieval-Methode nach Query/Dokument wählen.',
    outcome: 'choose retrieval method based on query/document properties.',
    conceptIds: ['CONCEPT-RET-003', 'CONCEPT-RET-004'], prerequisites: ['NODE-05-01'], unlocks: ['NODE-05-03'],
    labIds: [LAB.retrievalFactory], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-05-03', arcId: 'ARC-05', order: 21,
    title: 'Hybrid Search and Reranking',
    purpose: 'Evidenz-Qualität durch zweistufiges Retrieval verbessern.',
    outcome: 'improve evidence quality with two-stage retrieval.',
    conceptIds: ['CONCEPT-RET-005', 'CONCEPT-RET-006'], prerequisites: ['NODE-05-02'], unlocks: ['NODE-05-04'],
    labIds: [LAB.retrievalFactory], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-05-04', arcId: 'ARC-05', order: 22,
    title: 'Contextual Retrieval',
    purpose: 'Context-Verlust einzelner Chunks verhindern.',
    outcome: 'prevent chunk context loss.',
    conceptIds: ['CONCEPT-RET-007'], prerequisites: ['NODE-05-03'], unlocks: ['NODE-05-05'],
    labIds: [LAB.retrievalFactory], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-05-05', arcId: 'ARC-05', order: 23,
    title: 'Visual Document Retrieval',
    purpose: 'Wann Page-Image-Retrieval Text-Retrieval schlägt.',
    outcome: 'know when page-image retrieval beats text-only retrieval.',
    conceptIds: ['CONCEPT-RET-008', 'CONCEPT-RET-009'], prerequisites: ['NODE-05-04'], unlocks: ['NODE-06-01'],
    labIds: [LAB.paperFigureDecoder, LAB.retrievalFactory], lessonModes: ['paper-figure-decoder'],
  },
  {
    id: 'NODE-06-01', arcId: 'ARC-06', order: 24,
    title: 'Session vs Project Memory',
    purpose: 'Ephemeren Chat-Context von durable State trennen.',
    outcome: 'separate ephemeral chat context from durable state.',
    conceptIds: ['CONCEPT-MEM-001', 'CONCEPT-MEM-002'], prerequisites: ['NODE-05-05'], unlocks: ['NODE-06-02'],
    labIds: [LAB.repoRefactor], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-06-02', arcId: 'ARC-06', order: 25,
    title: 'Decision Logs and Feature Ledgers',
    purpose: 'Rationale und Implementierungs-Historie bewahren.',
    outcome: 'preserve rationale and implementation history.',
    conceptIds: ['CONCEPT-MEM-003', 'CONCEPT-MEM-004'], prerequisites: ['NODE-06-01'], unlocks: ['NODE-06-03'],
    labIds: [LAB.repoRefactor], lessonModes: ['worked-example'],
  },
  {
    id: 'NODE-06-03', arcId: 'ARC-06', order: 26,
    title: 'Agent Learning Loops',
    purpose: 'Wiederkehrende Fehler in durable Rules verwandeln.',
    outcome: 'convert repeated failures into durable rules.',
    conceptIds: ['CONCEPT-MEM-005'], prerequisites: ['NODE-06-02'], unlocks: ['NODE-06-04'],
    labIds: [LAB.repoRefactor], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-06-04', arcId: 'ARC-06', order: 27,
    title: 'Long-Running Agent Projects',
    purpose: 'Context-/Memory-/Control-Plane für Multi-Session entwerfen.',
    outcome: 'design context/memory/control plane for multi-session work.',
    conceptIds: ['CONCEPT-REPO-004'], prerequisites: ['NODE-06-03'], unlocks: ['NODE-07-01'],
    labIds: [LAB.repoRefactor, LAB.architectureBuilder], lessonModes: ['multiple-viewpoints'],
  },
  {
    id: 'NODE-07-01', arcId: 'ARC-07', order: 28,
    title: 'Eval Harness',
    purpose: 'Wiederholbare Messung entwerfen.',
    outcome: 'design repeatable measurement.',
    conceptIds: ['CONCEPT-EVAL-001'], prerequisites: ['NODE-06-04'], unlocks: ['NODE-07-02'],
    labIds: [LAB.evalDesigner], lessonModes: ['term-first', 'task-first'],
  },
  {
    id: 'NODE-07-02', arcId: 'ARC-07', order: 29,
    title: 'Task Success and Regression',
    purpose: 'Echte Outcomes messen und Regressionen verhindern.',
    outcome: 'measure real outcomes and prevent regressions.',
    conceptIds: ['CONCEPT-EVAL-002', 'CONCEPT-EVAL-004'], prerequisites: ['NODE-07-01'], unlocks: ['NODE-07-03'],
    labIds: [LAB.evalDesigner], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-07-03', arcId: 'ARC-07', order: 30,
    title: 'Grounding Evaluation',
    purpose: 'Aussagen gegen Quellen prüfen.',
    outcome: 'verify claims against sources.',
    conceptIds: ['CONCEPT-EVAL-003'], prerequisites: ['NODE-07-02'], unlocks: ['NODE-07-04'],
    labIds: [LAB.evalDesigner, LAB.retrievalFactory], lessonModes: ['worked-trace-first'],
  },
  {
    id: 'NODE-07-04', arcId: 'ARC-07', order: 31,
    title: 'Traces and Postmortems',
    purpose: 'Fehler debuggen und in System-Verbesserungen wandeln.',
    outcome: 'debug failures and convert them into system improvements.',
    conceptIds: ['CONCEPT-OBS-001', 'CONCEPT-OBS-002'], prerequisites: ['NODE-07-03'], unlocks: ['NODE-08-01'],
    labIds: [LAB.agentTraceDebugger, LAB.systemPostmortem], lessonModes: ['trace-first'],
  },
  {
    id: 'NODE-08-01', arcId: 'ARC-08', order: 32,
    title: 'Least Privilege',
    purpose: 'Tool-/Agent-Permissions minimieren.',
    outcome: 'minimize tool/agent permissions.',
    conceptIds: ['CONCEPT-SEC-001'], prerequisites: ['NODE-07-04'], unlocks: ['NODE-08-02'],
    labIds: [LAB.toolContractForge, LAB.securityIncidentRoom], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-08-02', arcId: 'ARC-08', order: 33,
    title: 'Human Approval Gates',
    purpose: 'Aktionen klassifizieren, die Approval brauchen.',
    outcome: 'classify actions requiring approval.',
    conceptIds: ['CONCEPT-SEC-002'], prerequisites: ['NODE-08-01'], unlocks: ['NODE-08-03'],
    labIds: [LAB.securityIncidentRoom], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-08-03', arcId: 'ARC-08', order: 34,
    title: 'Prompt Injection',
    purpose: 'Gegen manipulierende untrusted Inputs verteidigen.',
    outcome: 'defend against untrusted input manipulating agent/tool behavior.',
    conceptIds: ['CONCEPT-SEC-003'], prerequisites: ['NODE-08-02'], unlocks: ['NODE-08-04'],
    labIds: [LAB.incidentTriage, LAB.securityIncidentRoom, LAB.retrievalFactory], lessonModes: ['incident-first'],
  },
  {
    id: 'NODE-08-04', arcId: 'ARC-08', order: 35,
    title: 'Sandboxing and Governance',
    purpose: 'Sichere operative Grenzen entwerfen.',
    outcome: 'design safe operational boundaries.',
    conceptIds: ['CONCEPT-SEC-004', 'CONCEPT-PROD-003'], prerequisites: ['NODE-08-03'], unlocks: ['NODE-09-01'],
    labIds: [LAB.trustBoundary, LAB.securityIncidentRoom], lessonModes: ['multiple-viewpoints'],
  },
  {
    id: 'NODE-09-01', arcId: 'ARC-09', order: 36,
    title: 'Repo Legibility',
    purpose: 'Repo für Menschen und Agents lesbar machen.',
    outcome: 'make repo readable to humans and agents.',
    conceptIds: ['CONCEPT-REPO-001'], prerequisites: ['NODE-08-04'], unlocks: ['NODE-09-02'],
    labIds: [LAB.repoRefactor], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-09-02', arcId: 'ARC-09', order: 37,
    title: 'Conventions and Small Components',
    purpose: 'Monster-Files und instabile Muster verhindern.',
    outcome: 'prevent monster files and unstable patterns.',
    conceptIds: ['CONCEPT-REPO-002', 'CONCEPT-REPO-003'], prerequisites: ['NODE-09-01'], unlocks: ['NODE-09-03'],
    labIds: [LAB.repoRefactor], lessonModes: ['refactor-first'],
  },
  {
    id: 'NODE-09-03', arcId: 'ARC-09', order: 38,
    title: 'Source Material OS',
    purpose: 'Long-Context-Instruktionen als Control Plane verwalten.',
    outcome: 'manage long-context project instructions as control plane.',
    conceptIds: ['CONCEPT-REPO-004'], prerequisites: ['NODE-09-02'], unlocks: ['NODE-09-04'],
    labIds: [LAB.repoRefactor], lessonModes: ['worked-example'],
  },
  {
    id: 'NODE-09-04', arcId: 'ARC-09', order: 39,
    title: 'Team Scale',
    purpose: 'Für mehrere Menschen/Agents über Zeit entwerfen.',
    outcome: 'design for multiple humans/agents over time.',
    conceptIds: ['CONCEPT-PROD-003'], prerequisites: ['NODE-09-03'], unlocks: ['NODE-10-01'],
    labIds: [LAB.architectureBuilder], lessonModes: ['multiple-viewpoints'],
  },
  {
    id: 'NODE-10-01', arcId: 'ARC-10', order: 40,
    title: 'Capstone Briefing',
    purpose: 'Die finale System-Challenge verstehen.',
    outcome: 'understand final system challenge.',
    conceptIds: ['all_core'], prerequisites: ['NODE-09-04'], unlocks: ['NODE-10-02'],
    labIds: [LAB.capstoneSimulator], lessonModes: ['scenario-first'],
  },
  {
    id: 'NODE-10-02', arcId: 'ARC-10', order: 41,
    title: 'Capstone Architecture Draft',
    purpose: 'Ein erstes System vorschlagen.',
    outcome: 'propose initial system.',
    conceptIds: ['all_core'], prerequisites: ['NODE-10-01'], unlocks: ['NODE-10-03'],
    labIds: [LAB.capstoneSimulator], lessonModes: ['architecture-builder'],
  },
  {
    id: 'NODE-10-03', arcId: 'ARC-10', order: 42,
    title: 'Capstone Failure Injection',
    purpose: 'Fehler in der eigenen Architektur diagnostizieren.',
    outcome: 'diagnose failures in own architecture.',
    conceptIds: ['all_core'], prerequisites: ['NODE-10-02'], unlocks: ['NODE-10-04'],
    labIds: [LAB.securityIncidentRoom, LAB.agentTraceDebugger], lessonModes: ['incident-first'],
  },
  {
    id: 'NODE-10-04', arcId: 'ARC-10', order: 43,
    title: 'Capstone Eval and Governance',
    purpose: 'Messbare Verlässlichkeit und Kontrolle ergänzen.',
    outcome: 'add measurable reliability and control.',
    conceptIds: ['all_core'], prerequisites: ['NODE-10-03'], unlocks: ['NODE-10-05'],
    labIds: [LAB.evalDesigner], lessonModes: ['eval-first'],
  },
  {
    id: 'NODE-10-05', arcId: 'ARC-10', order: 44,
    title: 'Final System Review',
    purpose: 'Architektur mit Trade-offs und Failure Modes verteidigen.',
    outcome: 'defend architecture with trade-offs and failure modes.',
    conceptIds: ['all_core'], prerequisites: ['NODE-10-04'], unlocks: ['NODE-11-01'],
    labIds: [LAB.capstoneSimulator], lessonModes: ['postmortem'],
  },
  // ARC-11 — The Director's Seat (DIRECTION track, control/09 DIR-031..033). Additive arc
  // gated behind the capstone; reuses existing engines (curate / structure / oversight).
  {
    id: 'NODE-11-01', arcId: 'ARC-11', order: 45,
    title: 'From Builder to Director',
    purpose: 'Vom Selbst-Bauen zum Dirigieren wechseln: entscheiden, was der Agent sieht.',
    outcome: 'shift from building to directing: curate what the agent sees.',
    conceptIds: ['CONCEPT-DIR-001'], prerequisites: ['NODE-10-05'], unlocks: ['NODE-11-02'],
    labIds: [LAB.contextBudgetBoard], lessonModes: ['scenario-first'],
  },
  {
    id: 'NODE-11-02', arcId: 'ARC-11', order: 46,
    title: 'One Bee or Many',
    purpose: 'Ausführungsstruktur an den Task anpassen — Schwarm nur wenn er sich lohnt.',
    outcome: 'match execution structure to the task; do not over-swarm.',
    conceptIds: ['CONCEPT-DIR-002'], prerequisites: ['NODE-11-01'], unlocks: ['NODE-11-03'],
    labIds: [LAB.architectureBuilder], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-11-03', arcId: 'ARC-11', order: 47,
    title: 'Allocate Your Oversight',
    purpose: 'Knappe Aufsicht risikogewichtet verteilen statt gleichmäßig.',
    outcome: 'weight finite oversight by risk, not evenly.',
    conceptIds: ['CONCEPT-DIR-003'], prerequisites: ['NODE-11-02'], unlocks: ['NODE-11-04'],
    labIds: [LAB.contextAllocator], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-11-04', arcId: 'ARC-11', order: 48,
    title: 'Set the Delegation Boundaries',
    purpose: 'Vor dem Delegieren festlegen, was ein Agent darf, gated, gesandboxt oder isoliert.',
    outcome: 'set what a delegated agent may touch before it runs.',
    conceptIds: ['CONCEPT-DIR-004'], prerequisites: ['NODE-11-03'], unlocks: ['NODE-12-01'],
    labIds: [LAB.trustBoundary], lessonModes: ['task-first'],
  },
  // ARC-12 — Targeting the Swarm (DIRECTION track, control/09 DIR-032). Research-backed
  // (multi-source 2026): spec quality is the differentiator; coupling limits parallelism;
  // catch drift early. Reuses tradeOffDuel / pipelineBuilder / incidentTriage.
  {
    id: 'NODE-12-01', arcId: 'ARC-12', order: 49,
    title: 'The Brief Is the Bottleneck',
    purpose: 'Den Brief richtig dimensionieren — Output-Qualität hängt fast nur daran.',
    outcome: 'right-size the brief; output quality tracks spec quality, not model choice.',
    conceptIds: ['CONCEPT-DIR-005'], prerequisites: ['NODE-11-04'], unlocks: ['NODE-12-02'],
    labIds: [LAB.tradeOffDuel], lessonModes: ['trade-off-first'],
  },
  {
    id: 'NODE-12-02', arcId: 'ARC-12', order: 50,
    title: 'Sequence the Dependencies',
    purpose: 'Teilaufgaben abhängigkeits-respektierend ordnen; Scope-Creep weglassen.',
    outcome: 'order subtasks by dependency; cut scope creep.',
    conceptIds: ['CONCEPT-DIR-006'], prerequisites: ['NODE-12-01'], unlocks: ['NODE-12-03'],
    labIds: [LAB.pipelineBuilder], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-12-03', arcId: 'ARC-12', order: 51,
    title: 'Triage the Swarm',
    purpose: 'Knappe Aufmerksamkeit über parallele Agenten priorisieren — Drift zuerst.',
    outcome: 'prioritize attention across parallel agents; stop drift first.',
    conceptIds: ['CONCEPT-DIR-007'], prerequisites: ['NODE-12-02'], unlocks: ['NODE-13-01'],
    labIds: [LAB.incidentTriage], lessonModes: ['task-first'],
  },
  // ARC-13 — Delivery & Acceptance (DIRECTION track, control/09 DIR-017/018). The PM
  // delivery half on existing engines (scope via allocator, accept via trade-off-duel).
  {
    id: 'NODE-13-01', arcId: 'ARC-13', order: 52,
    title: 'Prioritize and Cut',
    purpose: 'Kapazität nach Wert × Risiko verteilen — den Kern finanzieren, Wenig-Wertvolles streichen.',
    outcome: 'allocate finite capacity by value × risk; cut the low-value.',
    conceptIds: ['CONCEPT-DIR-008'], prerequisites: ['NODE-12-03'], unlocks: ['NODE-13-02'],
    labIds: [LAB.contextAllocator], lessonModes: ['task-first'],
  },
  {
    id: 'NODE-13-02', arcId: 'ARC-13', order: 53,
    title: 'Accept or Send Back',
    purpose: 'Agent-Output gegen die Akzeptanzkriterien abnehmen — kein Rubber-Stamp, kein Nitpick.',
    outcome: 'accept against the brief; no rubber-stamp, no nitpick.',
    conceptIds: ['CONCEPT-DIR-009'], prerequisites: ['NODE-13-01'], unlocks: ['NODE-13-03'],
    labIds: [LAB.tradeOffDuel], lessonModes: ['task-first'],
  },
  // The DIRECT-A-BUILD round-trip — the Open-Claw exit proof (PC-043). One feature (2FA),
  // four phases (brief → decompose → diagnose → accept), four mechanics, one multi-challenge lesson.
  {
    id: 'NODE-13-03', arcId: 'ARC-13', order: 54,
    title: 'Direct the Build',
    purpose: 'Einen echten Feature-Build end-to-end dirigieren: briefen, zerlegen, diagnostizieren, abnehmen.',
    outcome: 'direct a real feature build end-to-end (spec → decompose → diagnose → accept).',
    conceptIds: ['all_core'], prerequisites: ['NODE-13-02'], unlocks: ['NODE-13-04'],
    labIds: [LAB.tradeOffDuel, LAB.pipelineBuilder, LAB.failureModeTree], lessonModes: ['scenario-first'],
  },
  // The PRODUCTION CAPSTONE — a stateful strategy game. Direct one whole product end-to-end;
  // decisions carry state (quality/security/scope/oversight), early shortcuts surface as late
  // incidents, a launch scorecard traces choices → outcome. Integrates every skill on a real build.
  {
    id: 'NODE-13-04', arcId: 'ARC-13', order: 55,
    title: 'Ship It: The Build Campaign',
    purpose: 'Ein ganzes Produkt als Strategiespiel dirigieren — jede Entscheidung trägt Folgen bis zum Launch-Scorecard.',
    outcome: 'direct an entire product build as a strategy game; decisions carry state to a launch scorecard.',
    conceptIds: ['all_core'], prerequisites: ['NODE-13-03'], unlocks: [],
    labIds: [], lessonModes: ['scenario-first'],
  },
]
