import type { LabScenario } from '@/features/labs/interactionModel'
import type { ArchScenarioData } from '@/features/labs/architectureBuilder/types'

// Architecture Builder scenarios. Intro at NODE-01-01 (workflow suffices) + a
// transfer where dynamic planning justifies an agent (LS-005, changed constraint).
export const architectureScenarios: LabScenario<ArchScenarioData>[] = [
  {
    id: 'AB-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-01-01',
    title: 'Architecture Builder',
    prompt:
      'Baue das einfachste System für einen FAQ-Assistenten über aktuelle interne Docs. Decke alle Capabilities ab — ohne Überbau.',
    concepts: ['CONCEPT-AIE-002', 'CONCEPT-AIE-003', 'CONCEPT-EVAL-001'],
    prerequisites: ['NODE-00-02'],
    difficulty: 'intro',
    estimatedMinutes: 7,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer', 'overengineering_repair'],
    scenarioData: {
      task: 'FAQ-Assistent über aktuelle interne Dokumente — vorhersehbarer Ablauf.',
      requiredCapabilities: ['answer', 'retrieval', 'eval'],
      forbiddenTypes: ['agent', 'subagent'],
      maxRecommended: 3,
      components: [
        { id: 'model', type: 'model', label: 'LLM', capabilities: ['answer'], cost: 'low' },
        { id: 'retriever', type: 'retrieval', label: 'Retriever', capabilities: ['retrieval'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'agent', type: 'agent', label: 'Autonomous Agent', capabilities: ['answer', 'planning'], cost: 'high', risk: 'Fehler-Aufschaukeln' },
        { id: 'memory', type: 'memory', label: 'Long-term Memory', capabilities: ['memory'], cost: 'medium' },
      ],
    },
  },
  {
    id: 'AB-TRANSFER',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-01-01',
    title: 'Architecture Builder — Transfer: Dynamic Planning',
    prompt:
      'Geändertes Szenario: offene, dynamische Aufgabe mit Tool-Einsatz. Jetzt ist Planung gefragt — wähle passend.',
    concepts: ['CONCEPT-CF-005', 'CONCEPT-EVAL-001'],
    prerequisites: ['NODE-00-02'],
    difficulty: 'core',
    estimatedMinutes: 7,
    isTransfer: true,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer'],
    scenarioData: {
      task: 'Offene Recherche-Aufgabe mit dynamischer Planung und Tool-Einsatz.',
      requiredCapabilities: ['answer', 'planning', 'tools', 'eval'],
      forbiddenTypes: [],
      maxRecommended: 4,
      components: [
        { id: 'model', type: 'model', label: 'LLM', capabilities: ['answer'], cost: 'low' },
        { id: 'agent', type: 'agent', label: 'Planner Agent', capabilities: ['planning'], cost: 'high', risk: 'mehr Kontrolle nötig' },
        { id: 'tool', type: 'tool', label: 'Tool Layer', capabilities: ['tools'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'retriever', type: 'retrieval', label: 'Retriever', capabilities: ['retrieval'], cost: 'low' },
      ],
    },
  },
  {
    id: 'WVA-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-04-01',
    title: 'Workflow vs Agent — Ticket-Pipeline',
    prompt:
      'Support-Tickets durchlaufen immer dieselben Schritte: extrahieren → kategorisieren → an die richtige Queue routen. Baue das einfachste System, das alle Schritte abdeckt.',
    concepts: ['CONCEPT-CF-001', 'CONCEPT-CF-002'],
    prerequisites: ['NODE-03-04'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer', 'overengineering_repair'],
    scenarioData: {
      task: 'Fester, vorhersehbarer Ablauf (extract → classify → route). Kein offenes Ziel, keine dynamische Planung.',
      requiredCapabilities: ['extract', 'classify', 'route', 'eval'],
      forbiddenTypes: ['agent', 'subagent'],
      maxRecommended: 4,
      components: [
        { id: 'extractor', type: 'tool', label: 'Feld-Extraktor', capabilities: ['extract'], cost: 'low' },
        { id: 'classifier', type: 'model', label: 'Klassifikator', capabilities: ['classify'], cost: 'low' },
        { id: 'router', type: 'workflow', label: 'Router (feste Regeln)', capabilities: ['route'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'agent', type: 'agent', label: 'Autonomer Agent', capabilities: ['extract', 'classify', 'route'], cost: 'high', risk: 'unnötige Autonomie für einen festen Ablauf — mehr Fehlerquellen, schwerer zu testen' },
        { id: 'memory', type: 'memory', label: 'Long-term Memory', capabilities: ['memory'], cost: 'medium' },
      ],
    },
  },
  {
    id: 'WFP-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-04-02',
    title: 'Workflow Patterns — Routing + Parallel',
    prompt:
      'Eine Anfrage wird auf einen festen Pfad geroutet und löst dort mehrere unabhängige Teilabfragen parallel aus. Komponiere die Pattern — ohne autonomen Agenten.',
    concepts: ['CONCEPT-CF-002', 'CONCEPT-CF-003'],
    prerequisites: ['NODE-04-01'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer'],
    scenarioData: {
      task: 'Bekannte Pfade (Routing) + feste, unabhängige Teilschritte (Parallelisierung). Der Kontrollfluss ist vorgegeben, nicht vom Modell geplant.',
      requiredCapabilities: ['route', 'parallelize', 'answer', 'eval'],
      forbiddenTypes: ['agent', 'subagent'],
      maxRecommended: 4,
      components: [
        { id: 'router', type: 'workflow', label: 'Router (Pfadwahl)', capabilities: ['route'], cost: 'low' },
        { id: 'fanout', type: 'workflow', label: 'Parallel Fan-out', capabilities: ['parallelize'], cost: 'low' },
        { id: 'model', type: 'model', label: 'LLM', capabilities: ['answer'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'agent', type: 'agent', label: 'Planner Agent', capabilities: ['route', 'parallelize', 'answer'], cost: 'high', risk: 'ersetzt einen festen Kontrollfluss durch teure, schwer testbare Autonomie' },
        { id: 'memory', type: 'memory', label: 'Session Memory', capabilities: ['memory'], cost: 'medium' },
      ],
    },
  },
  {
    id: 'ORW-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-04-03',
    title: 'Orchestrator–Worker — Parallele Recherche',
    prompt:
      'Eine offene Recherche zerfällt in mehrere unabhängige Teilfragen, deren Anzahl erst zur Laufzeit feststeht. Baue das System, das das tragfähig löst.',
    concepts: ['CONCEPT-CF-005'],
    prerequisites: ['NODE-04-02'],
    difficulty: 'advanced',
    estimatedMinutes: 7,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer'],
    scenarioData: {
      task: 'Dynamische Anzahl unabhängiger Teilfragen + Synthese. Hier rechtfertigt sich echte Delegation an isolierte Worker (anders als beim festen Ablauf).',
      requiredCapabilities: ['orchestration', 'research', 'synthesis', 'eval'],
      forbiddenTypes: [],
      maxRecommended: 3,
      components: [
        { id: 'orchestrator', type: 'agent', label: 'Orchestrator', capabilities: ['orchestration', 'synthesis'], cost: 'high' },
        { id: 'worker', type: 'subagent', label: 'Research-Worker (isoliert)', capabilities: ['research'], cost: 'medium' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'model', type: 'model', label: 'Einzelnes LLM', capabilities: ['answer'], cost: 'low', risk: 'deckt weder Orchestrierung noch parallele Recherche ab — unterdimensioniert' },
        { id: 'memory', type: 'memory', label: 'Long-term Memory', capabilities: ['memory'], cost: 'medium' },
      ],
    },
  },
  {
    id: 'MCP-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-03-04',
    title: 'MCP & Tool-Ökosysteme',
    prompt:
      'Dein Assistent muss auf mehrere externe Systeme (CRM, Kalender, Tickets) zugreifen. Baue die Tool-Schicht so einfach wie möglich.',
    concepts: ['CONCEPT-TOOL-005'],
    prerequisites: ['NODE-03-03'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer', 'overengineering_repair'],
    scenarioData: {
      task: 'Mehrere externe Systeme über EIN standardisiertes Protokoll (MCP) anbinden, statt N bespoke Integrationen zu pflegen.',
      requiredCapabilities: ['answer', 'tools', 'eval'],
      forbiddenTypes: [],
      maxRecommended: 3,
      components: [
        { id: 'model', type: 'model', label: 'LLM', capabilities: ['answer'], cost: 'low' },
        { id: 'mcp', type: 'tool', label: 'MCP-Tool-Layer (ein Protokoll)', capabilities: ['tools'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval Harness', capabilities: ['eval'], cost: 'low' },
        { id: 'bespoke', type: 'tool', label: 'Bespoke CRM-Integration', capabilities: ['tools'], cost: 'high', risk: 'redundant: dieselbe Capability schon über MCP — eigene Integration pro System skaliert schlecht' },
        { id: 'agent', type: 'agent', label: 'Autonomer Tool-Agent', capabilities: ['answer', 'tools'], cost: 'high', risk: 'Autonomie löst kein Anbindungsproblem, erhöht nur die Angriffsfläche' },
      ],
    },
  },
  {
    id: 'TSC-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-09-04',
    title: 'Scaling to a Team — Governance',
    prompt:
      'Das System geht von einem Power-User zu einem ganzen Team über. Baue es so, dass Qualität und riskante Aktionen unter mehr Last kontrolliert bleiben.',
    concepts: ['CONCEPT-REPO-004'],
    prerequisites: ['NODE-09-03'],
    difficulty: 'advanced',
    estimatedMinutes: 7,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['architecture_transfer'],
    scenarioData: {
      task: 'Mehr Nutzer, mehr riskante Aktionen. Skalierung heißt hier Governance (Approval, Guardrails, Evals) — nicht „mehr Modell-Kopien“.',
      requiredCapabilities: ['answer', 'approval', 'guardrail', 'eval'],
      forbiddenTypes: [],
      maxRecommended: 4,
      components: [
        { id: 'model', type: 'model', label: 'LLM', capabilities: ['answer'], cost: 'low' },
        { id: 'human', type: 'human', label: 'Human Approval Gate', capabilities: ['approval'], cost: 'medium' },
        { id: 'guardrail', type: 'guardrail', label: 'Policy-Guardrail', capabilities: ['guardrail'], cost: 'low' },
        { id: 'eval', type: 'eval', label: 'Eval + Regression Suite', capabilities: ['eval'], cost: 'low' },
        { id: 'replica', type: 'model', label: 'Zweite LLM-Kopie', capabilities: ['answer'], cost: 'high', risk: 'redundant: dieselbe Capability — Durchsatz löst kein Governance-Problem' },
        { id: 'agent', type: 'agent', label: 'Autonomer Team-Agent', capabilities: ['answer', 'approval'], cost: 'high', risk: 'ein Agent darf das Approval nicht selbst erteilen — Kontrolle gehört zum Menschen' },
      ],
    },
  },
  {
    id: 'DIR-SWARM-BASE',
    interactionType: 'architecture-builder',
    labId: 'LAB-ARCHITECTURE-BUILDER',
    roadmapNodeId: 'NODE-11-02',
    title: 'Eine Biene oder ein Schwarm?',
    prompt:
      'Ein klar umrissener, gut spezifizierter Auftrag. Wähle die einfachste Ausführungsstruktur, die ihn abdeckt — über-schwärme einen definierten Task nicht.',
    concepts: ['CONCEPT-DIR-002'],
    prerequisites: ['NODE-11-01'],
    difficulty: 'advanced',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'arch-default',
    feedbackProfileId: 'arch-default',
    reviewHooks: ['direction_transfer', 'overengineering_repair'],
    scenarioData: {
      task: 'Ein einzelner, klar spezifizierter Task (bekannte Schritte, ein Ergebnis). Als Director wählst du, wer ihn ausführt — nicht wie viele.',
      requiredCapabilities: ['execute', 'review'],
      forbiddenTypes: ['subagent'],
      maxRecommended: 2,
      components: [
        { id: 'executor', type: 'agent', label: 'Ein Ausführungs-Agent', capabilities: ['execute'], cost: 'medium' },
        { id: 'eval', type: 'eval', label: 'Eval / Acceptance-Check', capabilities: ['review'], cost: 'low' },
        { id: 'orchestrator', type: 'agent', label: 'Orchestrator obendrauf', capabilities: ['orchestration'], cost: 'high', risk: 'Koordinations-Overhead für einen einzelnen klaren Task — keine parallele Arbeit zu koordinieren' },
        { id: 'worker', type: 'subagent', label: 'Zusätzliche Worker-Bienen', capabilities: ['execute'], cost: 'high', risk: 'Über-Schwarm: mehrere Worker für einen Task, der seriell von einem erledigt wird' },
        { id: 'memory', type: 'memory', label: 'Long-term Memory', capabilities: ['memory'], cost: 'medium' },
      ],
    },
  },
]
