import type { LabScenario } from '@/features/labs/interactionModel'
import type { ContextBudgetData } from '@/features/labs/contextBudgetBoard/types'

// Context Budget Board scenarios. Base intro at NODE-02-01 + a tighter transfer
// variant that forces compression (LS-005, MECH-TRANSFER).
export const contextBudgetScenarios: LabScenario<ContextBudgetData>[] = [
  {
    id: 'CBB-BASE',
    interactionType: 'context-budget-board',
    labId: 'LAB-CONTEXT-BUDGET-BOARD',
    roadmapNodeId: 'NODE-02-01',
    title: 'Context Budget Board',
    prompt:
      'Stelle den Context für einen Coding-Agenten zusammen. Behalte, was die Aufgabe definiert — schließe Noise aus, bleib im Budget.',
    concepts: ['CONCEPT-CTX-001', 'CONCEPT-CTX-002', 'CONCEPT-CTX-003'],
    prerequisites: ['NODE-01-03'],
    difficulty: 'intro',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'cbb-default',
    feedbackProfileId: 'cbb-default',
    reviewHooks: ['context_noise_transfer', 'compression_loss_transfer'],
    scenarioData: {
      task: 'Implementiere ein neues API-Feld gemäß den aktiven Architektur-Constraints.',
      maxTokens: 8000,
      items: [
        { id: 'sys', label: 'System Prompt', sourceType: 'system', tokens: 800, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'task', label: 'Aktuelle Task-Spezifikation', sourceType: 'user', tokens: 600, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'constraints', label: 'Aktive Architektur-Constraints', sourceType: 'repo', tokens: 900, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true, compressible: true },
        { id: 'srcfile', label: 'Relevante Quelldatei', sourceType: 'repo', tokens: 1500, relevance: 2, noiseRisk: 0, staleRisk: 0, compressible: true },
        { id: 'history', label: 'Alter Chat-Verlauf', sourceType: 'history', tokens: 2600, relevance: 0, noiseRisk: 3, staleRisk: 2 },
        { id: 'todos', label: 'TODO-Notizen aus einem früheren Sprint', sourceType: 'memory', tokens: 700, relevance: 1, noiseRisk: 2, staleRisk: 3 },
        { id: 'marketing', label: 'Marketing-Doc zu einem anderen Produkt', sourceType: 'research', tokens: 1200, relevance: 0, noiseRisk: 3, staleRisk: 1 },
      ],
    },
  },
  {
    id: 'CBB-TRANSFER',
    interactionType: 'context-budget-board',
    labId: 'LAB-CONTEXT-BUDGET-BOARD',
    roadmapNodeId: 'NODE-02-01',
    title: 'Context Budget Board — Transfer: Source Selection',
    prompt:
      'Geändertes Szenario: knappes Budget, viele Quellen. Wähle Evidenz für eine Recherche — komprimiere Pflicht-Quellen statt sie zu droppen.',
    concepts: ['CONCEPT-CTX-002', 'CONCEPT-CTX-004'],
    prerequisites: ['NODE-01-03'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: true,
    scoringProfileId: 'cbb-default',
    feedbackProfileId: 'cbb-default',
    reviewHooks: ['compression_loss_transfer'],
    scenarioData: {
      task: 'Beantworte eine Recherchefrage gestützt auf zwei Schlüssel-Quellen — bei 4.000 Token Budget.',
      maxTokens: 4000,
      items: [
        { id: 'sys', label: 'System Prompt', sourceType: 'system', tokens: 400, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'question', label: 'Recherchefrage', sourceType: 'user', tokens: 300, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'paperA', label: 'Schlüssel-Quelle A', sourceType: 'research', tokens: 1500, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true, compressible: true },
        { id: 'paperB', label: 'Schlüssel-Quelle B', sourceType: 'research', tokens: 1400, relevance: 3, noiseRisk: 1, staleRisk: 0, compressible: true },
        { id: 'oldnotes', label: 'Notizen aus einer früheren Projektphase', sourceType: 'memory', tokens: 900, relevance: 1, noiseRisk: 2, staleRisk: 3 },
        { id: 'blog', label: 'Populärartikel zum Oberthema', sourceType: 'research', tokens: 1100, relevance: 0, noiseRisk: 3, staleRisk: 2 },
        { id: 'dump', label: 'Ungefilterte Suchergebnisse (Top-k)', sourceType: 'retrieval', tokens: 2200, relevance: 1, noiseRisk: 3, staleRisk: 1 },
      ],
    },
  },
  {
    id: 'CBN-BASE',
    interactionType: 'context-budget-board',
    labId: 'LAB-CONTEXT-BUDGET-BOARD',
    roadmapNodeId: 'NODE-02-02',
    title: 'Context Noise',
    prompt:
      'Das Budget reicht locker — das Problem ist Rauschen. Behalte das Signal, schließe die Noise-Quellen aus, damit die Antwort nicht abdriftet.',
    concepts: ['CONCEPT-CTX-003'],
    prerequisites: ['NODE-02-01'],
    difficulty: 'core',
    estimatedMinutes: 5,
    isTransfer: false,
    scoringProfileId: 'cbb-default',
    feedbackProfileId: 'cbb-default',
    reviewHooks: ['context_noise_transfer'],
    scenarioData: {
      task: 'Beantworte eine Support-Frage gestützt auf den richtigen KB-Artikel. Budget ist reichlich; entscheidend ist, Noise draußen zu lassen.',
      maxTokens: 8000,
      items: [
        { id: 'sys', label: 'System Prompt', sourceType: 'system', tokens: 700, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'question', label: 'Aktuelle User-Frage', sourceType: 'user', tokens: 400, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'kb', label: 'KB-Artikel zur gemeldeten Fehlermeldung', sourceType: 'retrieval', tokens: 1400, relevance: 3, noiseRisk: 0, staleRisk: 0 },
        { id: 'policy', label: 'Policy-Notiz zum betroffenen Feature', sourceType: 'repo', tokens: 1000, relevance: 2, noiseRisk: 0, staleRisk: 0, compressible: true },
        { id: 'oldchat', label: 'Chat-Verlauf einer früheren, anderen Anfrage', sourceType: 'history', tokens: 2600, relevance: 0, noiseRisk: 3, staleRisk: 2 },
        { id: 'promo', label: 'Marketing-Onepager zum selben Produkt', sourceType: 'research', tokens: 1200, relevance: 0, noiseRisk: 3, staleRisk: 1 },
        { id: 'dump', label: 'Volltext-Suche: Top-50 ungefiltert', sourceType: 'retrieval', tokens: 2000, relevance: 1, noiseRisk: 3, staleRisk: 1 },
      ],
    },
  },
  {
    id: 'CBC-BASE',
    interactionType: 'context-budget-board',
    labId: 'LAB-CONTEXT-BUDGET-BOARD',
    roadmapNodeId: 'NODE-02-03',
    title: 'Context Compression',
    prompt:
      'Die Pflicht-Quellen passen zusammen nicht ins Budget. Droppe sie nicht — komprimiere, was komprimierbar ist, und halte die Noise draußen.',
    concepts: ['CONCEPT-CTX-004'],
    prerequisites: ['NODE-02-02'],
    difficulty: 'core',
    estimatedMinutes: 5,
    isTransfer: false,
    scoringProfileId: 'cbb-default',
    feedbackProfileId: 'cbb-default',
    reviewHooks: ['compression_loss_transfer'],
    scenarioData: {
      task: 'Setze ein Feature gemäß zwei Pflicht-Specs um — bei nur 3.500 Token. Beide Specs sind nötig, passen aber unkomprimiert nicht zusammen hinein.',
      maxTokens: 3500,
      items: [
        { id: 'sys', label: 'System Prompt', sourceType: 'system', tokens: 400, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'task', label: 'Task-Spezifikation', sourceType: 'user', tokens: 300, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'specA', label: 'Pflicht-Spec A (lang)', sourceType: 'repo', tokens: 1800, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true, compressible: true },
        { id: 'specB', label: 'Pflicht-Spec B (lang)', sourceType: 'repo', tokens: 1500, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true, compressible: true },
        { id: 'oldnotes', label: 'Implementierungs-Notizen aus dem v1-Entwurf', sourceType: 'memory', tokens: 800, relevance: 1, noiseRisk: 2, staleRisk: 3 },
        { id: 'blog', label: 'Blog-Post zum allgemeinen Themenfeld', sourceType: 'research', tokens: 1000, relevance: 0, noiseRisk: 3, staleRisk: 1 },
      ],
    },
  },
  {
    id: 'DIR-FEED-BASE',
    interactionType: 'context-budget-board',
    labId: 'LAB-CONTEXT-BUDGET-BOARD',
    roadmapNodeId: 'NODE-11-01',
    title: 'Director — was du der Biene fütterst',
    prompt:
      'Du delegierst ein Feature an einen Agenten. Du entscheidest, was er sieht. Gib ihm das Signal, kompromiere das Lange-aber-Nötige, lass den Dump draußen.',
    concepts: ['CONCEPT-DIR-001'],
    prerequisites: ['NODE-10-05'],
    difficulty: 'advanced',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'cbb-default',
    feedbackProfileId: 'cbb-default',
    reviewHooks: ['context_noise_transfer', 'direction_transfer'],
    scenarioData: {
      task: 'Ein Agent implementiert ein neues API-Feld. Als Director stellst du den Context zusammen, den er bekommt — nicht alles, was existiert.',
      maxTokens: 8000,
      items: [
        { id: 'sys', label: 'System-Regeln für den Agenten', sourceType: 'system', tokens: 600, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'ticket', label: 'Das Feature-Ticket', sourceType: 'user', tokens: 500, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true },
        { id: 'spec', label: 'Autoritative API-Spezifikation', sourceType: 'repo', tokens: 2200, relevance: 3, noiseRisk: 0, staleRisk: 0, required: true, compressible: true },
        { id: 'code', label: 'Die betroffene Quelldatei', sourceType: 'repo', tokens: 1800, relevance: 2, noiseRisk: 0, staleRisk: 0, compressible: true },
        { id: 'slack', label: 'Mitschnitt einer Team-Diskussion', sourceType: 'history', tokens: 1500, relevance: 1, noiseRisk: 2, staleRisk: 1 },
        { id: 'olddesign', label: 'Verworfener Design-Entwurf (v1)', sourceType: 'memory', tokens: 900, relevance: 0, noiseRisk: 2, staleRisk: 3 },
        { id: 'dump', label: 'Kompletter Repo-Dump zur Sicherheit', sourceType: 'retrieval', tokens: 3000, relevance: 1, noiseRisk: 3, staleRisk: 1 },
      ],
    },
  },
]
