import type { LabScenario } from '@/features/labs/interactionModel'
import type { RefactorScenarioData } from '@/features/labs/repoRefactor/types'

// Repo Refactor scenarios (PHASE_6, PH-701). For each problem the learner picks the
// root-cause fix over a symptom patch or over-engineering. Base = a project losing
// durable state (06-arc, NODE-06-01); transfer = an agent-hostile, illegible repo
// (09-arc, NODE-09-01). Same 3 dimensions, different concrete problems.
export const repoRefactorScenarios: LabScenario<RefactorScenarioData>[] = [
  {
    id: 'RR-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-06-01',
    title: 'Repo Refactor Lab',
    prompt:
      'Sanier das Projekt: behebe jedes Problem auf seiner Ebene — durable State, kleine Units, lesbare Struktur.',
    concepts: ['CONCEPT-MEM-003', 'CONCEPT-MEM-004', 'CONCEPT-REPO-003'],
    prerequisites: ['NODE-06-01'],
    difficulty: 'core',
    estimatedMinutes: 7,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['source_material_transfer', 'conventions_transfer'],
    scenarioData: {
      repo: 'Ein agentengetriebenes Projekt nach mehreren Monaten: gewachsen, aber zunehmend schwer wartbar.',
      goal: 'Wartbar halten für Menschen und Agents über die Zeit.',
      stations: [
        {
          id: 'durable',
          dimension: 'durable_state_fit',
          label: 'Durable State',
          question: 'Architektur-Entscheidungen leben nur im Chat-Verlauf. Was tust du?',
          bestOptionId: 'decision-log',
          options: [
            { id: 'decision-log', label: 'Entscheidungen ins Decision-Log/Ledger schreiben', rationale: 'Passt: macht Rationale durable und über Sessions auffindbar.' },
            { id: 'rely-chat', label: 'Auf den Chat-Verlauf verlassen', rationale: 'Falle: Chat-Memory ist flüchtig — Entscheidungen gehen verloren.' },
            { id: 'longer-prompt', label: 'Den System-Prompt mit allen Entscheidungen füllen', rationale: 'Falle: bläht den Hot-Context auf und bleibt trotzdem nicht durable.' },
          ],
        },
        {
          id: 'components',
          dimension: 'small_components_fit',
          label: 'Kleine Units',
          question: 'Eine 700-Zeilen-Datei macht Orchestrierung + Tools + Parsing. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Nach Verantwortung in kleine Module splitten', rationale: 'Passt: isolierte, testbare Units; sichere Agent-Edits.' },
            { id: 'add-comments', label: 'Mehr Kommentare hinzufügen', rationale: 'Falle: Symptom — die Datei bleibt riskant zu ändern.' },
            { id: 'add-layer', label: 'Eine Abstraktionsschicht darüber legen', rationale: 'Falle: mehr Komplexität, das Monster-File bleibt.' },
          ],
        },
        {
          id: 'legibility',
          dimension: 'legibility_fit',
          label: 'Lesbarkeit',
          question: 'Der Agent re-implementiert vorhandene Utils, weil er sie nicht findet. Was tust du?',
          bestOptionId: 'feature-folders',
          options: [
            { id: 'feature-folders', label: 'Feature-Folder + klare Namen + vorhersehbare Orte', rationale: 'Passt: die Struktur zeigt die Architektur — Agent findet Vorhandenes.' },
            { id: 'longer-prompt', label: 'Dem Agenten jedes Mal sagen, wo was liegt', rationale: 'Falle: patcht das Symptom im Prompt, die Unlesbarkeit bleibt.' },
            { id: 'rename-random', label: 'Dateien neu durchnummerieren', rationale: 'Falle: Umbenennen ohne Struktur macht es nicht lesbarer.' },
          ],
        },
      ],
    },
  },
  {
    id: 'RR-TRANSFER',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-09-01',
    title: 'Repo Refactor — Transfer: Legible Repo',
    prompt:
      'Geänderter Fokus: gleiche Methode, anderes Repo. Behebe jedes Problem auf seiner Ebene.',
    concepts: ['CONCEPT-REPO-001', 'CONCEPT-REPO-002', 'CONCEPT-REPO-004'],
    prerequisites: ['NODE-09-01'],
    difficulty: 'advanced',
    estimatedMinutes: 6,
    isTransfer: true,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['repo_legibility_transfer', 'source_material_transfer'],
    scenarioData: {
      repo: 'Eine Feature-Codebasis mit flachen Ordnern, duplizierten Regeln und einem überladenen Component.',
      goal: 'Repo für Menschen und Agents lesbar und sicher änderbar machen.',
      stations: [
        {
          id: 'durable',
          dimension: 'durable_state_fit',
          label: 'Durable State',
          question: 'Dieselbe Konvention steht in drei Docs, die Versionen driften. Was tust du?',
          bestOptionId: 'owner-doc',
          options: [
            { id: 'owner-doc', label: 'Eine Owner-Doc; andere referenzieren per Regel-ID', rationale: 'Passt: eine autoritative Quelle, keine widersprüchlichen Kopien.' },
            { id: 'keep-in-sync', label: 'Alle drei Kopien aktuell halten', rationale: 'Falle: Versionen driften auseinander, Agents lesen Widersprüche.' },
            { id: 'delete-rule', label: 'Die Regel überall löschen', rationale: 'Falle: die Konvention geht verloren statt konsolidiert zu werden.' },
          ],
        },
        {
          id: 'components',
          dimension: 'small_components_fit',
          label: 'Kleine Units',
          question: 'Ein 800-Zeilen-Component macht UI + Fetching + Scoring. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Nach Verantwortung trennen (UI / Logik / Content)', rationale: 'Passt: kleine, testbare Units; lokale, sichere Änderungen.' },
            { id: 'add-comments', label: 'Mehr Kommentare hinzufügen', rationale: 'Falle: Symptom — die Änderung bleibt riskant.' },
            { id: 'add-layer', label: 'Einen Wrapper darüber bauen', rationale: 'Falle: mehr Komplexität, das Monster-File bleibt.' },
          ],
        },
        {
          id: 'legibility',
          dimension: 'legibility_fit',
          label: 'Lesbarkeit',
          question: 'Flacher utils-Dump mit vagen Namen; der Agent missversteht die Architektur. Was tust du?',
          bestOptionId: 'feature-folders',
          options: [
            { id: 'feature-folders', label: 'Feature-Folder + klare, sprechende Namen', rationale: 'Passt: vorhersehbare Orte; der richtige Ort wird offensichtlich.' },
            { id: 'longer-prompt', label: 'Dem Agenten längere Erklär-Prompts geben', rationale: 'Falle: kompensiert die Unlesbarkeit nur, behebt sie nicht.' },
            { id: 'rename-random', label: 'Dateien zufällig umbenennen', rationale: 'Falle: ohne Struktur kein Gewinn an Lesbarkeit.' },
          ],
        },
      ],
    },
  },
  {
    id: 'DLL-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-06-02',
    title: 'Decision Logs & Ledgers',
    prompt: 'Mach das Warum hinter Entscheidungen durable und auffindbar — ohne den Hot-Context aufzublähen.',
    concepts: ['CONCEPT-MEM-004'],
    prerequisites: ['NODE-06-01'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['source_material_transfer'],
    scenarioData: {
      repo: 'Ein Projekt, in dem Architektur-Entscheidungen nirgends festgehalten sind.',
      goal: 'Entscheidungen + Begründungen über Sessions und Personen hinweg verfügbar halten.',
      stations: [
        {
          id: 'durable', dimension: 'durable_state_fit', label: 'Durable State',
          question: 'Niemand weiß mehr, warum Modul X so gebaut wurde. Was tust du?',
          bestOptionId: 'decision-log',
          options: [
            { id: 'decision-log', label: 'Entscheidung + Begründung als datierten Ledger-Eintrag festhalten', rationale: 'Passt: das Warum (inkl. verworfener Alternativen) wird durable und auffindbar.' },
            { id: 'ask-author', label: 'Bei Bedarf den ursprünglichen Autor fragen', rationale: 'Falle: Tribal Knowledge — bricht, sobald die Person wechselt.' },
            { id: 'code-comment', label: 'Einen Kommentar an den Code schreiben', rationale: 'Falle: erklärt die Zeile, nicht die System-Entscheidung und ihre Alternativen.' },
          ],
        },
        {
          id: 'components', dimension: 'small_components_fit', label: 'Kleine Units',
          question: 'Das Ledger ist eine einzige 1.500-Zeilen-Datei. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Pro Arc/Domain ein eigenes Ledger-File mit IDs', rationale: 'Passt: gezielt auffindbar statt linear durchsuchen.' },
            { id: 'toc-only', label: 'Ein Inhaltsverzeichnis oben anfügen', rationale: 'Falle: Symptom — die Datei bleibt ein Monolith.' },
            { id: 'archive-old', label: 'Ältere Einträge löschen', rationale: 'Falle: verliert die Historie, die den Ledger erst wertvoll macht.' },
          ],
        },
        {
          id: 'legibility', dimension: 'legibility_fit', label: 'Lesbarkeit',
          question: 'Entscheidungen liegen mal im Code, mal im Chat, mal im Ticket. Was tust du?',
          bestOptionId: 'single-source',
          options: [
            { id: 'single-source', label: 'Eine autoritative Ledger-Quelle; anderswo nur per ID referenzieren', rationale: 'Passt: eine Wahrheit, keine driftenden Kopien.' },
            { id: 'link-all', label: 'Alle Orte gegenseitig verlinken', rationale: 'Falle: die Versionen driften weiter, nur mit mehr Links.' },
            { id: 'prompt-tell', label: 'Dem Agenten sagen, wo er suchen soll', rationale: 'Falle: patcht das Symptom im Prompt, die Zersplitterung bleibt.' },
          ],
        },
      ],
    },
  },
  {
    id: 'AGL-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-06-03',
    title: 'Agent Learning Loops',
    prompt: 'Verwandle wiederkehrende Fehler in durable Lehren, die der Agent bei der passenden Aufgabe wirklich nutzt.',
    concepts: ['CONCEPT-MEM-003'],
    prerequisites: ['NODE-06-02'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['source_material_transfer', 'postmortem_transfer'],
    scenarioData: {
      repo: 'Ein agentengetriebenes Projekt, in dem dieselben Fehler immer wiederkehren.',
      goal: 'Aus Vorfällen durable Lehren machen, die zur richtigen Zeit greifen.',
      stations: [
        {
          id: 'durable', dimension: 'durable_state_fit', label: 'Durable State',
          question: 'Ein Agent macht denselben Fehler in jeder Session neu. Was tust du?',
          bestOptionId: 'rule-from-incident',
          options: [
            { id: 'rule-from-incident', label: 'Den Fall als datierte Regel + Gegenmaßnahme ins Learning-Log schreiben', rationale: 'Passt: macht die Lehre durable, statt sie pro Session zu verlieren.' },
            { id: 'retrain-hope', label: 'Darauf vertrauen, dass das Modell mit der Zeit dazulernt', rationale: 'Falle: das Modell ist zwischen Sessions stateless — es lernt nichts von selbst.' },
            { id: 'stuff-prompt', label: 'Den System-Prompt mit immer mehr Dauerwarnungen füllen', rationale: 'Falle: bläht den Hot-Context auf und bleibt unstrukturiert.' },
          ],
        },
        {
          id: 'components', dimension: 'small_components_fit', label: 'Kleine Units',
          question: 'Das Learning-Log mischt Prozess-Lehren, Bugfixes und Architektur. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Nach Typ trennen: process / content / architecture', rationale: 'Passt: gezielt auffindbar, gezielt anwendbar.' },
            { id: 'one-list', label: 'Alles in einer chronologischen Liste lassen', rationale: 'Falle: die relevante Lehre verschwindet im Strom.' },
            { id: 'delete-resolved', label: 'Gelöste Einträge sofort entfernen', rationale: 'Falle: löscht genau das Muster, das die Wiederkehr zeigt.' },
          ],
        },
        {
          id: 'legibility', dimension: 'legibility_fit', label: 'Lesbarkeit',
          question: 'Niemand schaut ins Learning-Log, bevor er eine ähnliche Aufgabe startet. Was tust du?',
          bestOptionId: 'route-on-task',
          options: [
            { id: 'route-on-task', label: 'Relevante Lehren per Tag bei der passenden Aufgabe einblenden', rationale: 'Passt: die Lehre kommt zur richtigen Zeit, ohne Dauerlast.' },
            { id: 'load-all', label: 'Das ganze Log immer in den Context laden', rationale: 'Falle: erzeugt Noise und verdrängt die Aufgabe.' },
            { id: 'manual-remember', label: 'Darauf bauen, dass sich die Leute erinnern', rationale: 'Falle: Tribal Knowledge — genau das hat schon versagt.' },
          ],
        },
      ],
    },
  },
  {
    id: 'LRP-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-06-04',
    title: 'Long-running Projects',
    prompt: 'Halte den Projektzustand über Monate kohärent — für Menschen und Agents, die später einsteigen.',
    concepts: ['CONCEPT-MEM-004', 'CONCEPT-REPO-003'],
    prerequisites: ['NODE-06-03'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['source_material_transfer', 'conventions_transfer'],
    scenarioData: {
      repo: 'Ein Projekt im fünften Monat: gewachsen, mit driftenden Notizen und einer großen Orchestrierungsdatei.',
      goal: 'Über Monate verständlich, konsistent und sicher änderbar bleiben.',
      stations: [
        {
          id: 'durable', dimension: 'durable_state_fit', label: 'Durable State',
          question: 'Aktuelle Praxis und alte Notizen widersprechen sich. Was tust du?',
          bestOptionId: 'reconcile',
          options: [
            { id: 'reconcile', label: 'Widersprüche in einer autoritativen Quelle auflösen und datieren', rationale: 'Passt: ein konsistenter, aktueller Stand statt mehrerer Wahrheiten.' },
            { id: 'keep-both', label: 'Beide Stände nebeneinander behalten', rationale: 'Falle: die Drift wächst weiter, Leser raten.' },
            { id: 'trust-chat', label: 'Dem neuesten Chat-Verlauf vertrauen', rationale: 'Falle: flüchtig — der nächste Monat verliert ihn wieder.' },
          ],
        },
        {
          id: 'components', dimension: 'small_components_fit', label: 'Kleine Units',
          question: 'Eine Orchestrierungsdatei ist über Monate auf 900 Zeilen gewachsen. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Nach Verantwortung in kleine Module splitten', rationale: 'Passt: lokale, testbare, agent-sichere Änderungen.' },
            { id: 'comment', label: 'Abschnitts-Kommentare einziehen', rationale: 'Falle: Symptom — die Änderung bleibt riskant.' },
            { id: 'wrapper', label: 'Eine Fassade darüber legen', rationale: 'Falle: mehr Komplexität, das Monster-File bleibt.' },
          ],
        },
        {
          id: 'legibility', dimension: 'legibility_fit', label: 'Lesbarkeit',
          question: 'Ein neuer Agent braucht Stunden, um den Projektstand zu verstehen. Was tust du?',
          bestOptionId: 'state-doc',
          options: [
            { id: 'state-doc', label: 'Ein knapper, aktueller „State of the Project“-Einstieg mit Verweisen', rationale: 'Passt: ein vorhersehbarer Startpunkt führt schnell zum Relevanten.' },
            { id: 'read-history', label: 'Den gesamten Verlauf durchlesen lassen', rationale: 'Falle: teuer und voller Noise — der Stand bleibt unklar.' },
            { id: 'ask-maintainer', label: 'Den Maintainer fragen', rationale: 'Falle: macht eine Person zum Bottleneck und Single Point of Failure.' },
          ],
        },
      ],
    },
  },
  {
    id: 'CSC-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-09-02',
    title: 'Conventions & Small Components',
    prompt: 'Mach das Repo agent-sicher änderbar: kleine Units, dokumentierte Konventionen, vorhersehbare Orte.',
    concepts: ['CONCEPT-REPO-002'],
    prerequisites: ['NODE-09-01'],
    difficulty: 'core',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['conventions_transfer', 'repo_legibility_transfer'],
    scenarioData: {
      repo: 'Eine Codebasis mit einem überladenen Component und ungeschriebenen Konventionen.',
      goal: 'Für Menschen und Agents sicher und lokal änderbar machen.',
      stations: [
        {
          id: 'components', dimension: 'small_components_fit', label: 'Kleine Units',
          question: 'Ein 800-Zeilen-Component macht UI + Fetching + Scoring. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'Nach Verantwortung trennen (UI / Logik / Content)', rationale: 'Passt: kleine, testbare Units; ein Agent kann lokal sicher ändern.' },
            { id: 'comment', label: 'Mehr Kommentare hinzufügen', rationale: 'Falle: Symptom — die Änderung bleibt riskant.' },
            { id: 'wrapper', label: 'Einen Wrapper darüber bauen', rationale: 'Falle: mehr Komplexität, das Monster-File bleibt.' },
          ],
        },
        {
          id: 'durable', dimension: 'durable_state_fit', label: 'Durable State',
          question: 'Die Ablage-/Namens-Konvention lebt nur im Kopf des Lead-Devs. Was tust du?',
          bestOptionId: 'convention-doc',
          options: [
            { id: 'convention-doc', label: 'Die Konvention als Regel mit ID dokumentieren', rationale: 'Passt: durable und für Mensch wie Agent nachprüfbar.' },
            { id: 'ask-lead', label: 'Im Zweifel den Lead-Dev fragen', rationale: 'Falle: Tribal Knowledge — bricht beim Team-Wachstum.' },
            { id: 'lint-only', label: 'Einen Linter für den Stil anschalten', rationale: 'Falle: ein Linter prüft Stil, nicht die Architektur-/Ablage-Konvention.' },
          ],
        },
        {
          id: 'legibility', dimension: 'legibility_fit', label: 'Lesbarkeit',
          question: 'Komponenten liegen in einem flachen Ordner mit vagen Namen. Was tust du?',
          bestOptionId: 'feature-folders',
          options: [
            { id: 'feature-folders', label: 'Feature-Folder + klare, sprechende Namen', rationale: 'Passt: der richtige Ort wird offensichtlich, auch für den Agenten.' },
            { id: 'prompt-tell', label: 'Dem Agenten die Pfade jedes Mal nennen', rationale: 'Falle: kompensiert die Unlesbarkeit, behebt sie nicht.' },
            { id: 'rename-random', label: 'Dateien neu durchnummerieren', rationale: 'Falle: Umbenennen ohne Struktur bringt nichts.' },
          ],
        },
      ],
    },
  },
  {
    id: 'SMO-BASE',
    interactionType: 'repo-refactor-lab',
    labId: 'LAB-REPO-REFACTOR',
    roadmapNodeId: 'NODE-09-03',
    title: 'Source-Material OS',
    prompt: 'Mach die Steuer-Docs zur Control Plane: kompakt, autoritativ, on-demand statt allgegenwärtig.',
    concepts: ['CONCEPT-REPO-003', 'CONCEPT-REPO-004'],
    prerequisites: ['NODE-09-02'],
    difficulty: 'advanced',
    estimatedMinutes: 6,
    isTransfer: false,
    scoringProfileId: 'rr-default',
    feedbackProfileId: 'rr-default',
    reviewHooks: ['source_material_transfer', 'repo_legibility_transfer'],
    scenarioData: {
      repo: 'Ein Projekt, dessen Steuerregeln für Agents über README, Issues und Chat verstreut sind.',
      goal: 'Eine lesbare Control Plane, die Mensch und Agent zuverlässig steuert.',
      stations: [
        {
          id: 'durable', dimension: 'durable_state_fit', label: 'Durable State',
          question: 'Die Agent-Steuerregeln sind über README, Issues und Chat verstreut. Was tust du?',
          bestOptionId: 'control-plane',
          options: [
            { id: 'control-plane', label: 'Eine Source-Material control plane: kompakte Regel-Docs mit IDs', rationale: 'Passt: autoritativ, versioniert, von Menschen und Agents lesbar.' },
            { id: 'readme-dump', label: 'Alles in eine große README packen', rationale: 'Falle: unauffindbar — ein Wall of Text steuert nichts.' },
            { id: 'chat-pin', label: 'Das Wichtigste im Chat anpinnen', rationale: 'Falle: flüchtig und nicht versioniert.' },
          ],
        },
        {
          id: 'components', dimension: 'small_components_fit', label: 'Kleine Units',
          question: 'Ein einziges 2.000-Zeilen-Steuer-Doc deckt alles ab. Was tust du?',
          bestOptionId: 'split',
          options: [
            { id: 'split', label: 'In spezialisierte Docs nach Zweck trennen, per ID verlinkt', rationale: 'Passt: gezielt ladbar, gezielt pflegbar.' },
            { id: 'toc', label: 'Ein Inhaltsverzeichnis voranstellen', rationale: 'Falle: Symptom — das Doc bleibt ein Monolith.' },
            { id: 'archive', label: 'Selten genutzte Abschnitte löschen', rationale: 'Falle: verliert Regeln, statt sie zu ordnen.' },
          ],
        },
        {
          id: 'legibility', dimension: 'legibility_fit', label: 'Lesbarkeit',
          question: 'Agents laden bei jeder Aufgabe das komplette Regelwerk. Was tust du?',
          bestOptionId: 'load-on-demand',
          options: [
            { id: 'load-on-demand', label: 'Nur die für die Aufgabe relevanten Docs laden (Load-Priority/Routing)', rationale: 'Passt: bounded Context, die richtige Regel zur richtigen Zeit.' },
            { id: 'load-all', label: 'Immer das ganze Regelwerk laden', rationale: 'Falle: Context-Noise und unnötige Kosten.' },
            { id: 'inline-prompt', label: 'Alle Regeln in den System-Prompt inlinen', rationale: 'Falle: bläht den Hot-Context dauerhaft auf.' },
          ],
        },
      ],
    },
  },
]
